name: verificacao_estoque_online
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  crypto: ^3.0.1
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  date_format: ^2.0.4
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  syncfusion_flutter_charts: ^19.2.62
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  local_auth: ^2.1.3
  liquid_swipe: ^3.1.0
  flutter_masked_text2: ^0.9.1
  flutter_typeahead: ^3.2.1
  carousel_slider: ^4.0.0
  transparent_image: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0
  unique_identifier: ^0.3.0
 # imei_plugin: ^1.2.0
  device_information: ^0.0.4
 # android_multiple_identifier: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/
    

  fonts:
   # - family: CustomIcons
    #  fonts:
     #   - asset: assets/icons/CustomIcons.ttf

    - family: Kastelov
      fonts:
        - asset: lib/assets/fonts/Kastelov-Axiforma-Regular.otf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
